services:
  db:
    build: .
    container_name: pgvector-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/00-init.sql
    # Use our wrapper so we can run SQL every start
    entrypoint: ["/usr/local/bin/always.sh"]
    command: ["postgres"]
volumes:
  pg_data:
